services:
  - type: web
    name: wsbs-backend
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PAYMONGO_PUBLIC_KEY
        sync: false
      - key: PAYMONGO_SECRET_KEY
        sync: false
      - key: PAYMONGO_WEBHOOK_SECRET
        sync: false
      - key: PAYMONGO_MODE
        value: test
      - key: DB_HOST
        fromDatabase:
          name: wsbs-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: wsbs-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: wsbs-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: wsbs-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: wsbs-db
          property: password

  - type: web
    name: wsbs-admin
    env: static
    rootDir: admin
    buildCommand: "npm install && npm run build"
    staticPublishPath: build

databases:
  - name: wsbs-db
    databaseName: wsbs
