import React from 'react';
import '../styles/Reports.css';

const Reports = () => {
  // Sample report data
  const reports = [
    {
      id: 'RPT-001',
      type: 'Waste Collection',
      period: 'Weekly',
      generatedBy: 'Admin User',
      date: '26/09/24 - 10:46 AM',
      status: 'Completed'
    },
    {
      id: 'RPT-002',
      type: 'User Activity',
      period: 'Monthly',
      generatedBy: 'System Auto',
      date: '25/09/24 - 09:30 AM',
      status: 'Completed'
    },
    {
      id: 'RPT-003',
      type: 'Financial Summary',
      period: 'Quarterly',
      generatedBy: 'Finance Team',
      date: '20/09/24 - 03:15 PM',
      status: 'Pending Review'
    },
    {
      id: 'RPT-004',
      type: 'Partner Performance',
      period: 'Monthly',
      generatedBy: 'Admin User',
      date: '18/09/24 - 11:20 AM',
      status: 'Completed'
    },
    {
      id: 'RPT-005',
      type: 'Route Efficiency',
      period: 'Weekly',
      generatedBy: 'Operations',
      date: '15/09/24 - 02:00 PM',
      status: 'Completed'
    },
    {
      id: 'RPT-006',
      type: 'Waste Composition',
      period: 'Annual',
      generatedBy: 'Research Team',
      date: '10/09/24 - 04:45 PM',
      status: 'Draft'
    }
  ];

  return (
        <section className="reports-content">
          <div className="reports-header">
            <h3>Generated Reports</h3>
            <div className="report-actions">
              <button className="generate-btn">+ Generate New Report</button>
              <input type="text" placeholder="Search reports..." />
              <select>
                <option>All Types</option>
                <option>Waste Collection</option>
                <option>User Activity</option>
                <option>Financial</option>
              </select>
              <select>
                <option>All Status</option>
                <option>Completed</option>
                <option>Pending</option>
                <option>Draft</option>
              </select>
            </div>
          </div>
          
          <table className="reports-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Report Type</th>
                <th>Period</th>
                <th>Generated By</th>
                <th>Date Generated</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report) => (
                <tr key={report.id}>
                  <td>{report.id}</td>
                  <td>{report.type}</td>
                  <td>{report.period}</td>
                  <td>{report.generatedBy}</td>
                  <td>{report.date}</td>
                  <td>
                    <span className={`status-badge ${report.status.toLowerCase().replace(' ', '-')}`}>
                      {report.status}
                    </span>
                  </td>
                  <td>
                    <button className="action-btn view">View</button>
                    <button className="action-btn download">Download</button>
                    <button className="action-btn delete">Delete</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          
          <div className="pagination">
            <span>Showing 1 to 6 of 6 entries</span>
            <div className="pagination-controls">
              <button disabled>Previous</button>
              <button className="active">1</button>
              <button>Next</button>
            </div>
          </div>
        </section>
  );
};

export default Reports;