name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'WSBS/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'WSBS/package-lock.json'
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install dependencies
      working-directory: ./WSBS
      run: npm ci
      
    - name: Setup Expo CLI
      run: npm install -g @expo/cli
      
    - name: Prebuild Android
      working-directory: ./WSBS
      run: npx expo prebuild --platform android --clear
      
    - name: Build Android APK
      working-directory: ./WSBS/android
      run: ./gradlew assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: wsbs-production-apk
        path: WSBS/android/app/build/outputs/apk/release/app-release.apk
